### ISSUE TITLE
Last line of code

### ISSUE THREAD

**Issue by RJeremias1** [maxmind/geolite2-ws-blogpost#2]
Hi,
I have gone through all the steps in this program without too much issue. When I got to the last line of code, though, I got this message:
"'MM_ACCOUNT_ID' is not recognized as an internal or external command, operable program or batch file."
Any ideas on how to resolve this issue?

Thanks!

**Comment by oschwald** [comment]
`MM_ACCOUNT_ID` should be set as an environment variable. Please see [the blog post](https://blog.maxmind.com/2021/01/integrating-maxminds-free-and-paid-ip-geolocation-web-services-in-php/#:~:text=1-,MM_ACCOUNT_ID,-%3DYOURACCOUNTID%20MM_LICENSE_KEY).
